if: tag IS blank # don't build tags
language: cpp
sudo: true # travis-ci/travis-ci#9033
os: linux
compiler: gcc

notifications:
  email:
    on_success: change
    on_failure: always
git:
  depth: 5

addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - llvm-toolchain-trusty-4.0
      - llvm-toolchain-trusty-5.0


matrix:
  include:
    # GCC 5
    - env: COMPILER=g++-5
      compiler: gcc
      addons: &gcc5
        apt:
          packages: ["g++-5", "valgrind"]
          sources: *apt_sources

    # GCC 6
    - env: COMPILER=g++-6
      compiler: gcc
      addons: &gcc6
        apt:
          packages: ["g++-6", "valgrind"]
          sources: *apt_sources

    # GCC 7
    - env: COMPILER=g++-7
      compiler: gcc
      addons: &gcc7
        apt:
          packages: ["g++-7", "valgrind"]
          sources: *apt_sources

    # Clang 4.0
    - env: COMPILER=clang++-4.0 ADDITIONAL_CXX_FLAGS="-g -fno-omit-frame-pointer -fsanitize=address,undefined"
      addons: &clang40
        apt:
          packages: ["clang-4.0", "valgrind", "g++-6"]
          sources: *apt_sources

    # Clang 5.0
    - env: COMPILER=clang++-5.0 ADDITIONAL_CXX_FLAGS="-g -fno-omit-frame-pointer -fsanitize=address,undefined"
      addons: &clang50
        apt:
          packages: ["clang-5.0", "valgrind", "g++-6"]
          sources: *apt_sources

    # Xcode 9.2 Clang
    - env: COMPILER=clang++ ADDITIONAL_CXX_FLAGS="-g -fno-omit-frame-pointer -fsanitize=address,undefined"
      osx_image: xcode9.2
      os: osx

before_script:
  - ${COMPILER} --version
  - cmake --version

script:
  # sanitize options
  - export ASAN_OPTIONS=allow_addr2line=true:check_initialization_order=true:strict_init_order=true:strict_string_checks=true:detect_odr_violation=2:detect_stack_use_after_return=true:verbosity=0
  # tests
  - mkdir -p dbg_build
  - cd dbg_build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. -DPICOBENCH_BUILD_TOOLS=1 -DPICOBENCH_BUILD_TESTS=1 -DPICOBENCH_BUILD_EXAMPLES=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="${ADDITIONAL_CXX_FLAGS}"
  - make -j2
  - cd test
  - ctest --output-on-failure
  - cd ../..
  - mkdir -p release_build
  - cd release_build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. -DPICOBENCH_BUILD_TOOLS=1 -DPICOBENCH_BUILD_TESTS=1 -DPICOBENCH_BUILD_EXAMPLES=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="${ADDITIONAL_CXX_FLAGS}"
  - make -j2
  - cd test
  - ctest --output-on_failure
  - cd ..
  # examples
  - cd example
  - ./basic
  - cd ..
  # tools
  - cd tools
  - ./picobench "sleep 0.3" "sleep 0.22"
  - cd ..
