[book]
authors = ["rogeryoungh"]
language = "zh-cn"
multilingual = false
src = "src"
title = "Roger Young 的板子"

[preprocessor.katex]

[output.html]
git-repository-url = "https://github.com/rogeryoungh/code-of-acm/"
edit-url-template = "https://github.com/rogeryoungh/code-of-acm/edit/main/{path}"

[output.html.fold]
enable = true
level = 2
