add_rules("mode.debug", "mode.release")

set_optimize("faster") -- O2
add_cxxflags("-Wall", "-Wextra", "-Wshadow")
set_languages("c99", "c++20")

target("src")
    set_kind("object")
    add_includedirs("src/", {public = true})
    add_includedirs("picobench/include", {public = true})

target("ntt-newton")
    set_kind("binary")
    add_deps("src")
    add_files("src/poly/ntt-newton-test.cpp")
    on_run(function (target)
        os.run("./build/linux/x86_64/release/ntt-newton --output=build/poly-ntt-newton.info")
    end)

target("ntt-newton-fast")
    set_kind("binary")
    add_deps("src")
    add_files("src/poly/ntt-newton-fast-test.cpp")
    on_run(function (target)
        os.run("./build/linux/x86_64/release/ntt-newton-fast --output=build/poly-ntt-newton-fast.info")
    end)

target("ntt-newton-blockwise-fast")
    set_kind("binary")
    add_deps("src")
    add_files("src/poly/ntt-newton-blockwise-fast-test.cpp")
    on_run(function (target)
        os.run("./build/linux/x86_64/release/ntt-newton-blockwise-fast --output=build/ntt-newton-blockwise-fast.info")
    end)

target("ntt-naive")
    set_kind("binary")
    add_deps("src")
    add_files("src/poly/ntt-naive-test.cpp")
    on_run(function (target)
        os.run("./build/linux/x86_64/release/ntt-naive --output=build/ntt-naive.info")
    end)

target("ntt-mul-mod3")
    set_kind("binary")
    add_deps("src")
    add_files("src/poly/ntt-mul-mod3-test.cpp")
    on_run(function (target)
        os.run("./build/linux/x86_64/release/ntt-mul-mod3 --output=build/ntt-mul-mod3.info")
    end)

target("ntt-mul-i32")
    set_kind("binary")
    add_deps("src")
    add_files("src/poly/ntt-mul-i32-test.cpp")
    on_run(function (target)
        os.run("./build/linux/x86_64/release/ntt-mul-i32 --output=build/ntt-mul-i32.info")
    end)

target("ntt-eval")
    set_kind("binary")
    add_deps("src")
    add_files("src/poly/ntt-eval-test.cpp")
    on_run(function (target)
        os.run("./build/linux/x86_64/release/ntt-eval --output=build/ntt-eval.info")
    end)

target("relax/ntt-semi")
    set_kind("binary")
    add_deps("src")
    add_files("src/poly/relax/ntt-semi-test.cpp")
    on_run(function (target)
        os.run("./build/linux/x86_64/release/relax/ntt-semi --output=build/ntt-semi.info")
    end)

target("relax/ntt-semi-fast")
    set_kind("binary")
    add_deps("src")
    add_files("src/poly/relax/ntt-semi-fast-test.cpp")
    on_run(function (target)
        os.run("./build/linux/x86_64/release/relax/ntt-semi-fast --output=build/ntt-semi-fast.info")
    end)

target("relax/ntt-relax")
    set_kind("binary")
    add_deps("src")
    add_files("src/poly/relax/ntt-relax-test.cpp")
    on_run(function (target)
        os.run("./build/linux/x86_64/release/relax/ntt-relax --output=build/ntt-relax.info")
    end)

target("fft-mul")
    set_kind("binary")
    add_deps("src")
    add_files("src/poly/fft-mul-test.cpp")
    on_run(function (target)
        os.run("./build/linux/x86_64/release/fft-mul --output=build/fft-mul.info")
    end)
